version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: skilvorae_mysql
    restart: always
    environment:
      MYSQL_DATABASE: skilvoraedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: skilvorae
      MYSQL_PASSWORD: skilvorae123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  skilvorae-app:
    build: .
    container_name: skilvorae_app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/skilvoraedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

volumes:
  mysql_data:
